using System;

namespace ClaraMundi
{
    [Serializable]
    public class QuestTaskProgress
    {
        public string PlayerName;
        // Task completions should be cleared from the database once a
        // Quest completion is saved, because we don't need to track
        // Task progress at that point. This way we can save space on the
        // database a bit
        public string QuestId;
        public string QuestTaskId;
        // Volatile completions should not be persisted to the database,
        // rather it should be generated by conditions on the quest
        // as it pertains to the task details
        // IE: items held is in memory, not persistent
        public bool IsVolatile;
        
        // deem the task completed by checking the task requirement
        public bool DialogueCompleted;
        public int DispatchCount = 0;
        public int ItemsHeld = 0;
        public bool ItemsTurnedIn;
    }
}